name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false
      - uses: golangci/golangci-lint-action@v9
      - run: make TEST_OPTS='-race -coverprofile=coverage.txt'
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run benchmark
        run: |
          make bench | tee bench.log
          echo '### Benchmark results' >> $GITHUB_STEP_SUMMARY
          echo '```'                   >> $GITHUB_STEP_SUMMARY
          go version                   >> $GITHUB_STEP_SUMMARY
          cat bench.log                >> $GITHUB_STEP_SUMMARY
          echo '```'                   >> $GITHUB_STEP_SUMMARY
